# Generated by Django 5.2.8 on 2025-11-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(blank=True, choices=[('generalist', 'Generalist'), ('oncologist', 'Oncologist'), ('cardiologist', 'Cardiologist'), ('pediatrician', 'Pediatrician'), ('neurologist', 'Neurologist'), ('endocrinologist', 'Endocrinologist'), ('pulmonologist', 'Pulmonologist'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
