# Generated by Django 5.2.8 on 2025-12-28 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
