# Generated by Django 5.2.8 on 2025-11-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_rare', models.BooleanField(default=False)),
                ('orpha_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
