# Generated by Django 5.2.8 on 2025-12-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='recommended_specialty',
            field=models.CharField(blank=True, choices=[('generalist', 'Generalist'), ('oncologist', 'Oncologist'), ('cardiologist', 'Cardiologist'), ('pediatrician', 'Pediatrician'), ('neurologist', 'Neurologist'), ('endocrinologist', 'Endocrinologist'), ('pulmonologist', 'Pulmonologist'), ('other', 'Other')], help_text='Specialist type usually needed for this disease.', max_length=50, null=True),
        ),
    ]
